[project]
name = "SystemCmd-z7"
version = "7.2"
authors = [{name = "Andrea Censi", email = "info@zupermind.com"}]
dependencies = ["zuper-commons-z7"]

[project.scripts]

[tool]
[tool.poetry]
name = "SystemCmd-z7"
version = "7.2"
description = ""
authors = ["Andrea Censi <info@zupermind.com>"]
packages = [{include = "system_cmd", from = "src"}]

[tool.setuptools]
packages = ["system_cmd"]
package-dir = {"" = "src"}
